#!/usr/bin/env python3

import os
from colorama import Fore
print(Fore.GREEN)
print()
print("Types of hash codes: md5sum, sha256sum, etc.")
print()
password = str(input("Enter Pasword: "))
type = str(input("Enter Hash Type: "))
print()
maker = os.system(f'echo -n "{password}" | {type} >> hashfile{type}.txt')
print()
password2 = str(input("Enter Password #2: "))
maker = os.system(f'echo -n "{password2}" | {type} >> hashfile{type}.txt')
print()
password3 = str(input("Enter Password #3: "))
maker = os.system(f'echo -n "{password3}" | {type} >> hashfile{type}.txt')
print()
password4 = str(input("Enter Password #4: "))
maker = os.system(f'echo -n "{password4}" | {type} >> hashfile{type}.txt')
print()
password5 = str(input("Enter Password #5: "))
maker = os.system(f'echo -n "{password5}" | {type} >> hashfile{type}.txt')
print()
password6 = str(input("Enter Password #6: "))
maker = os.system(f'echo -n "{password6}" | {type} >> hashfile{type}.txt')
print()
password7 = str(input("Enter Password #7: "))
maker = os.system(f'echo -n "{password7}" | {type} >> hashfile{type}.txt')
print()
password8 = str(input("Enter Password #8: "))
maker = os.system(f'echo -n "{password8}" | {type} >> hashfile{type}.txt')
print()
password9 = str(input("Enter Password #9: "))
maker = os.system(f'echo -n "{password9}" | {type} >> hashfile{type}.txt')
print()
password10 = str(input("Enter Password #10: "))
maker = os.system(f'echo -n "{password10}" | {type} >> hashfile{type}.txt')
print()
print(Fore.RED)
print(f"10 {type} hashes done.")